### ISSUE TITLE
conventional changelog support

### ISSUE THREAD

**Issue by NewFuture** [Roang-zero1/github-create-release-action#1]
https://github.com/conventional-changelog/conventional-changelog/blob/master/packages/conventional-changelog/CHANGELOG.md

tag: `v1.0.0`
markdown:
```md
## [1.0.0](https://github.com/angular/angular/compare/v1.0.0...v0.0.0) (2019-09-08)
```
## [1.0.0](https://github.com) (2019-09-08)

how to config this?

**Comment by Roang-zero1** [comment]
Sorry for the late reply, I overlooked the notification mail.

_Quick question regarding this issue:_  
The GitHub releases page does not allow a link in the release title as it always links to the tag e.g. v1.0.0 always links to `https://github.com/<org>/<repo>/releases/tag/v1.0.0`.

So the first thing I will implement is a Prefix and suffix for the tag and replace the title, but the additional information would not be possible in the way you requested.
My proposal is to add a flag `CHANGELOG_INCLUDE_TITLE` that would then include the whole markdown formatted title in the release notes.

**Comment by Roang-zero1** [comment]
Parsing of conventional-changelog is soft-depended on https://github.com/dahlia/submark/issues/2 getting fixed

**Comment by NewFuture** [comment]
thanks

**Comment by mfasman95** [comment]
Have there been any updates on this issue? This would be very useful for me.

**Comment by Roang-zero1** [comment]
As this has been fixed upstream, this is now possible as of version [`2.2.0`](https://github.com/Roang-zero1/github-create-release-action/releases/tag/v2.2.0)
