### ISSUE TITLE
Add option to pass tag from other action

### ISSUE THREAD

**Issue by Roang-zero1** [Roang-zero1/github-create-release-action#2]
As seen on https://github.com/serucee/github-create-release-action, it should be possible to pass the tag from another action

@serucee: Would you be interested in creating a pull request with an optional input for the tag?

**Comment by serucee** [comment]
Hi @Roang-zero1 ,
I will open a PR next week.

BR

**Comment by serucee** [comment]
Hi @Roang-zero1 ,

I started a [branch](https://github.com/serucee/github-create-release-action/tree/Optional-entrypoint) today, will test it tomorrow, if everything works out I will open the PR.
For a full example why I added the option to pass the tag checkout [Create Release Workflow](https://github.com/serucee/github-actions/blob/master/.github/workflows/create_release.yml)

BR

**Comment by serucee** [comment]
@Roang-zero1 Hi,

do you know when you will get to review/merge? We are kind of waiting for this feature so we can fork a save state.

BR

**Comment by Roang-zero1** [comment]
Sorry, didn't get the notification on the PR.
I am currently travelling, but will review it either today or tomorrow in the evening.

**Comment by Roang-zero1** [comment]
Update has been released as [v2.1.0](https://github.com/Roang-zero1/github-create-release-action/releases/tag/v2.1.0)
