### ISSUE TITLE
Is this possible for this action not to fail if push wasn't a tag?

### ISSUE THREAD

**Issue by ghost** [Roang-zero1/github-create-release-action#8]
I can see how this will drown my mailbox in spam... why does it have to fail if a push wasn't a tag?

**Comment by rpsu** [comment]
you should be able to run the action only on certain events. 
https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#using-filters-to-target-specific-branches-or-tags-for-push-events

**Comment by ghost** [comment]
Sorry, I think I figured it out a while ago. This can be closed.

**Comment by Roang-zero1** [comment]
Thanks @rpsu for the solution.
Will close the issue.

**Comment by Roang-zero1** [comment]
I've updated the readme to better reflect how to use this action.
